export enum Color {
  black = 'black',
  green = 'green',
  yellow = 'yellow',
  white = 'white',
  purple = 'purple',
  red = 'red',
  spacegray = 'spacegray',
  midnightgreen = 'midnightgreen',
  gold = 'gold',
  silver = 'silver',
  rosegold = 'rosegold',
  coral = 'coral',
  midnight = 'midnight',
  spaceblack = 'spaceblack',
  blue = 'blue',
  pink = 'pink',
  graphite = 'graphite',
  sierrablue = 'sierrablue',
}
